version: '3.8'

services:
  api:
    container_name: trackerService.api
    build:
      context: .
      dockerfile: ./tracker/Dockerfile
    restart: on-failure
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: ["main"]
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./usr/local/bin/prod.toml}